apiVersion: v1
kind: PersistentVolume
metadata:
  name: dyanca-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/dyanca-pv-1
---    
apiVersion: v1
kind: Namespace
metadata:
  name: dyanca
  namespace: dyanca
